name: 'Early Access'

on:
  push:
    branches: [ main ]

jobs:
  precheck:
    name: Precheck
    # early-access builds only enabled in canonical repository
    if: github.repository == 'tedneward/TicTacToeREST' && startsWith(github.event.head_commit.message, 'Releasing version') != true
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Version
        id: vars
        shell: bash
        run: |
          version=$(sed -n 's/version="\(.*\)"/\1/p' server/Ballerina.toml | head -n1)
          echo ::set-output name=VERSION::$(echo "$version")

  release:
    name: Release
    needs: [precheck]
    # run only if version is snapshot
    if: endsWith(${{ needs.precheck.outputs.VERSION }}, '-SNAPSHOT')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: ballerina-platform/ballerina-action@2201.1.1
        with:
          args: build
        env:
          WORKING_DIR: server

      - name: Release
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties